version: "3.9"

services:
  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    container_name: keydb
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    ports:
      - "6379:6379"
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  data:
    driver: local
  postgres: